- hosts: local
  become: yes
  roles:
    - ansible-role-nodejs

- hosts: db
  become: yes
  vars:
    mysql_users:
      - name: devel
        host: "%"
        password: devel
        priv: "citos.*:ALL"
    mysql_databases:
      - name: citos
  roles:
    - ansible-role-mysql
  tasks:
    - name: 'Import file.sql similar to mysql -u <username> -p <password> < hostname.sql'
      mysql_db:
        state: import
        name: citos
        target: /home/vagrant/test/setup.sql
      # mysql_db: "state=import name=all target=/home/vagrant/test/setup.sql"
      # command: "mysql -u{{ mysql_users.name }} -p{{ mysql_users.password }} citos < setup.sql"
      # args:
      #   chdir: "/home/vagrant/test"